[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure the mockServiceWorker.js file is available
[[headers]]
  for = "/mockServiceWorker.js"
  [headers.values]
    Cache-Control = "no-store"
    Content-Type = "application/javascript"
